// Copyright 2021 The Tiyo authors
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Package config defines the primary configuration structure loaded from
// JSON configuration either in the current working directory or in
// `/etc/tiyo/tiyo.yaml`
package config

import (
	"fmt"
	"io/ioutil"
	"os"
	"strings"
	"time"

	log "github.com/sirupsen/logrus"
	"gopkg.in/yaml.v3"
)

// TIMEOUT : Default timeout for http requests
const (
	TIMEOUT             time.Duration = 5 * time.Second
	SESSION_COOKIE_NAME string        = "__tiyo_session"
	SSO_SESSION_NAME    string        = "__tiyo_sso_session"
)

var Designate string = ""

// Host : Define how a host should be configured
//
// A host is one of `assemble` or `flow` and will contain
// information on how to start the host.
// If Cacert and CaKey are defined and not empty, the host
// will start on an SSL encrypted channel. This is the
// recommended behaviour in all instances, particularly for
// the assemble server which encrypts user provided passwords
// over the wire.
type Host struct {

	// The hostname to run the server on
	Hostname string `yaml:"host"`

	// The port to listen on. For assemble, the default is 8180
	// and for flow the default is 8280.
	Port int `yaml:"port"`

	// An optional certificate to encrypt traffic into the host
	Cacert string `yaml:"cacert,omitempty"`

	// An optional certificate key - mutually inclusive with Cacert
	Cakey string `yaml:"cakey,omitempty"`

	// A passphrase to encrypt user provided credentials
	//
	// For assemble, this should be a secure passphrase, normally
	// generated as the output of `pwgen -synr \`\"\\ 20 1`
	//
	// For flow, this should be the encrypted version of the same
	// password which can be generated by running `tiyo encrypt primary`
	// after completing the assemble config
	Passphrase string `yaml:"passphrase,omitempty"`

	// ClientSecure - syphon required switch for http(s)
	ClientSecure bool `yaml:"secure,omitempty"`
}

// Kubernetes : Define the connection to the kubernetes cluster
type Kubernetes struct {

	// A path to the kubernetes cluster config to use
	ConfigFile string `yaml:"kubeconfig"`

	// The principle namespace to deploy into
	Namespace string `yaml:"namespace"`

	// The data-volume to mount
	Volume string `yaml:"volume"`
}

// Docker : Configiration for the Docker client
type Docker struct {

	// Docker registry to use. Default for this is dockerhub
	Registry string `yaml:"registry"`

	// The username to log in to the docker registry with
	Username string `yaml:"username"`

	// Api token to authenticate against the registry
	Token string `yaml:"token"`

	// Principle location for upstream containers.
	//
	// When defined, this will be used as a source for listing
	// containers in the `applications` sidebar, and a primary
	// source for all vanilla containers.
	Upstream string `yaml:"upstream"`

	// The location to store all containers built by the tiyo
	// flow server. Most containers in this location would normally
	// include `tiyo syphon` as their `ps 1`
	Primary string `yaml:"primary"`

	// Set to true if both primary and upstream are the same location
	SameSource bool `default:"false"`
}

// Config : Primary configuration object
type Config struct {

	// Defines the primary location on the fileserver
	// for files to be stored
	SequenceBaseDir string `yaml:"sequenceBaseDir"`

	// If true, will configure an nginx server running in
	// the same location as flow server for access to services
	// running inside the cluster.
	ExternalNginx bool `yaml:"externalNginx"`

	// The name of the database file
	Dbname string `yaml:"dbname"`

	// If true will skip certificate checking
	UseInsecureTLS bool `yaml:"skipVerify"`

	// Host configuration for the flow server
	Flow Host `yaml:"server"`

	// Kubernetes configuration
	Kubernetes *Kubernetes `yaml:"kubernetes,omitempty"`

	// Docker configuration
	Docker Docker `yaml:"docker"`

	// AppName for testing syphon locally
	AppName string `yaml:"appname"`

	// Primary DNS name for services
	DNSName string `yaml:"dnsName"`

	// Config for SAML 2fa
	SAML *SAML `yaml:"samli,omitempty"`

	// Contains a string map of schema URIs to URL locations
	Schemas map[string]string `yaml:"schemas"`

	// Base directory for configuration files - default /etc/tiyo
	ConfigBase string

	// Base directory for the database and container creation - default /var/tiyo
	DbDir string

	// Timeout - constant TIMEOUT
	TIMEOUT time.Duration
}

// NewConfig : Create a new configuration object and load the config file
func NewConfig() (*Config, error) {
	config := Config{
		DNSName:    "example.com",
		ConfigBase: "/etc/tiyo",
		DbDir:      "/var/tiyo",
		TIMEOUT:    TIMEOUT,
	}
	var (
		err        error
		configfile string = "tiyo.yaml"
	)
	_, err = os.Stat(configfile)
	if os.IsNotExist(err) {
		configfile = config.ConfigBase + "/" + configfile
	}

	log.Info("Using config file: ", configfile)
	yamlFile, err := os.Open(configfile)
	if err != nil {
		return nil, err
	}

	defer yamlFile.Close()
	byteValue, _ := ioutil.ReadAll(yamlFile)
	yaml.Unmarshal([]byte(byteValue), &config)

	if len(strings.Split(config.Flow.Hostname, ".")) == 1 {
		config.Flow.Hostname = config.Flow.Hostname + "." + config.DNSName
	}

	if config.Docker.Upstream == "" && config.Docker.Primary != "" {
		config.Docker.Upstream = config.Docker.Primary
	} else if config.Docker.Primary == "" && config.Docker.Upstream != "" {
		config.Docker.Primary = config.Docker.Upstream
	}

	if config.Docker.Upstream == config.Docker.Primary {
		config.Docker.SameSource = true
	}

	var home string
	if home, err = os.UserHomeDir(); err != nil {
		// assume running as root
		home = "/root"
	}

	if config.Kubernetes != nil {
		if config.Kubernetes.Namespace == "" {
			config.Kubernetes.Namespace = "default"
		}

		if config.Kubernetes.ConfigFile == "" {
			config.Kubernetes.ConfigFile = "config"
		}

		if _, err = os.Stat(config.Kubernetes.ConfigFile); os.IsNotExist(err) {
			var kubeconfig = config.ConfigBase + "/" + config.Kubernetes.ConfigFile
			if _, err = os.Stat(kubeconfig); os.IsNotExist(err) {
				config.Kubernetes.ConfigFile = home + "/.kube/" + config.Kubernetes.ConfigFile
			} else {
				config.Kubernetes.ConfigFile = kubeconfig
			}

			if _, err = os.Stat(config.Kubernetes.ConfigFile); os.IsNotExist(err) {
				return nil, err
			}
		}
	}

	return &config, nil
}

// FlowServer : Get the address of the flow FlowServer
func (config *Config) Address() string {
	var protocol string = "http"
	if config.Flow.ClientSecure || (config.Flow.Cacert != "" && config.Flow.Cakey != "") {
		protocol = "https"
	}
	host := fmt.Sprintf("%s://%s:%d", protocol, config.Flow.Hostname, config.Flow.Port)
	return host
}
